service: serverless-vpc-app

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  environment:
    QUEUE_URL:
      Ref: MyQueue
    TABLE_NAME: ProcessedData
  vpc:
    subnetIds:
      - subnet-054ea8bc80bb19191   
      - subnet-0faaeb7ce2e664bca
    securityGroupIds:
      - sg-06fcde170d797075b        
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
          Resource:
            - Fn::GetAtt:
                - MyQueue
                - Arn
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:eu-west-2:*:table/ProcessedData
        - Effect: Allow
          Action:
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DeleteNetworkInterface
          Resource: "*"

functions:
  warmer:
    handler: warmer/handler.handler
    events:
      - schedule: rate(5 minutes)

  receiver:
    handler: receiver/handler.handler
    events:
      - http:
          path: receive
          method: post
          cors: true

  processor:
    handler: processor/handler.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn

  dbApi:
    handler: dbApi/handler.handler
    events:
      - http:
          path: data
          method: get
          cors: true
      - http:
          path: data
          method: put
          cors: true 
      - http: 
          path: data/{id}
          method: delete
          cors: true  

resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MyProcessingQueue

    MyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProcessedData
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
