name: Deploy Serverless App

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize project (first time only)
        run: |
          if [ ! -f package.json ]; then
            npm init -y
          fi

      - name: Install AWS SDK dependencies
        run: npm install @aws-sdk/client-sqs @aws-sdk/client-dynamodb

      - name: Deploy using Serverless Framework
        run: serverless deploy
